"""Initial schema

Revision ID: 83cb8df21f9d
Revises: 
Create Date: 2026-10-02 12:21:00.988068

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '83cb8df21f9d'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('couples',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sync_changes',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('entity_type', sa.String(), nullable=False),
    sa.Column('entity_id', sa.String(), nullable=False),
    sa.Column('scope_type', sa.String(), nullable=False),
    sa.Column('scope_id', sa.UUID(), nullable=False),
    sa.Column('operation', sa.String(), nullable=False),
    sa.Column('version', sa.BigInteger(), autoincrement=True, nullable=True),
    sa.Column('changed_at', sa.DateTime(), nullable=False),
    sa.Column('changed_by', sa.UUID(), nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sync_changes_entity_id'), 'sync_changes', ['entity_id'], unique=False)
    op.create_index(op.f('ix_sync_changes_entity_type'), 'sync_changes', ['entity_type'], unique=False)
    op.create_index(op.f('ix_sync_changes_scope_id'), 'sync_changes', ['scope_id'], unique=False)
    op.create_index(op.f('ix_sync_changes_scope_type'), 'sync_changes', ['scope_type'], unique=False)
    op.create_index(op.f('ix_sync_changes_version'), 'sync_changes', ['version'], unique=True)
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('display_name', sa.String(), nullable=False),
    sa.Column('password_hash', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('couple_members',
    sa.Column('couple_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('role', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['couple_id'], ['couples.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('couple_id', 'user_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('couple_members')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_sync_changes_version'), table_name='sync_changes')
    op.drop_index(op.f('ix_sync_changes_scope_type'), table_name='sync_changes')
    op.drop_index(op.f('ix_sync_changes_scope_id'), table_name='sync_changes')
    op.drop_index(op.f('ix_sync_changes_entity_type'), table_name='sync_changes')
    op.drop_index(op.f('ix_sync_changes_entity_id'), table_name='sync_changes')
    op.drop_table('sync_changes')
    op.drop_table('couples')
    # ### end Alembic commands ###
