"""add couple lifecycle fields

Revision ID: cf3eb4481f16
Revises: e3f456789012
Create Date: 2026-10-03 00:02:40.967665

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cf3eb4481f16'
down_revision: Union[str, Sequence[str], None] = 'e3f456789012'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('couples', sa.Column('status', sa.String(), nullable=False))
    op.add_column('couples', sa.Column('invite_code', sa.String(), nullable=True))
    op.add_column('couples', sa.Column('invite_expires_at', sa.DateTime(), nullable=True))
    op.create_index(op.f('ix_couples_invite_code'), 'couples', ['invite_code'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_couples_invite_code'), table_name='couples')
    op.drop_column('couples', 'invite_expires_at')
    op.drop_column('couples', 'invite_code')
    op.drop_column('couples', 'status')
    # ### end Alembic commands ###
